// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using kurssienhallinta.Models;

#nullable disable

namespace kurssienhallinta.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251118153037_CreateRooms")]
    partial class CreateRooms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("kurssienhallinta.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Day_of_end")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Day_of_start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Day_of_end = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Day_of_start = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Näe terävästi ja opettele hianoo kieltä.",
                            Name = "C# kurssi."
                        },
                        new
                        {
                            Id = 2,
                            Day_of_end = new DateTime(9001, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Day_of_start = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Opetellaan tunnistamaan sieniä, syömään sieniä, arvostamaan sieniä, rihmastoitumaan.",
                            Name = "Sienestyskurssi"
                        });
                });

            modelBuilder.Entity("kurssienhallinta.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Room_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 100,
                            Name = "Opetus Tila_0",
                            Room_code = "OpT0"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 1,
                            Name = "Kapselihotelli",
                            Room_code = "Kp0"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
