// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using kurssienhallinta.Models;

#nullable disable

namespace kurssienhallinta.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("kurssienhallinta.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Day_of_end")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Day_of_start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Day_of_end = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Day_of_start = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Näe terävästi ja opettele hianoo kieltä.",
                            Name = "C# kurssi."
                        },
                        new
                        {
                            Id = 2,
                            Day_of_end = new DateTime(9001, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Day_of_start = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Opetellaan tunnistamaan sieniä, syömään sieniä, arvostamaan sieniä, rihmastoitumaan.",
                            Name = "Sienestyskurssi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
